[package]
name = "power"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyrun-plugin = { git = "https://github.com/anyrun-org/anyrun" }
abi_stable = "0.11.1"
fuzzy-matcher = "0.3.7"
ron = "0.12.0"
serde = "1.0.228"
